name: 'Check for Changes (Build, K8s, CloudFormation)'
description: 'Detects changes in build files, k8s manifests, and CloudFormation templates'
inputs:
  k8s-path:
    description: 'Path pattern for k8s files (default: .k8s/)'
    required: false
    default: '.k8s/'
  cf-file:
    description: 'CloudFormation file name to check (default: aws-resources.yaml)'
    required: false
    default: 'aws-resources.yaml'
  event-name:
    description: 'GitHub event name (defaults to github.event_name)'
    required: false
    default: ''
  event-before:
    description: 'Git commit SHA before (defaults to github.event.before)'
    required: false
    default: ''
  event-sha:
    description: 'Git commit SHA (defaults to github.sha)'
    required: false
    default: ''

outputs:
  build_container:
    description: 'Whether container should be built (true/false)'
    value: ${{ steps.filter.outputs.build_container }}
  k8s_changed:
    description: 'Whether k8s files changed (true/false)'
    value: ${{ steps.filter.outputs.k8s_changed }}
  cf_changed:
    description: 'Whether CloudFormation changed (true/false)'
    value: ${{ steps.filter.outputs.cf_changed }}
  config_changed_non_prod:
    description: 'Whether non-prod ConfigMap or SealedSecret files changed (true/false)'
    value: ${{ steps.filter.outputs.config_changed_non_prod }}
  config_changed_prod:
    description: 'Whether prod ConfigMap or SealedSecret files changed (true/false)'
    value: ${{ steps.filter.outputs.config_changed_prod }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Check for all changes
      id: filter
      shell: bash
      run: |
        set -euo pipefail

        # Get event parameters with fallbacks
        event_name="${{ inputs.event-name }}"
        [ -z "$event_name" ] && event_name="${{ github.event_name }}"

        event_before="${{ inputs.event-before }}"
        [ -z "$event_before" ] && event_before="${{ github.event.before }}"

        event_sha="${{ inputs.event-sha }}"
        [ -z "$event_sha" ] && event_sha="${{ github.sha }}"

        k8s_path="${{ inputs.k8s-path }}"
        cf_file="${{ inputs.cf-file }}"

        echo "=== Change Detection Results ==="
        echo "Event: $event_name"
        echo "Comparing: $event_before...$event_sha"
        echo ""

        # Enable all jobs for manual runs or when we can't determine changes
        if [[ "$event_name" == "workflow_dispatch" ]] || [[ -z "$event_before" ]] || [[ "$event_before" =~ ^0+$ ]]; then
          if [[ "$event_name" == "workflow_dispatch" ]]; then
            echo "Manual run detected - enabling all jobs"
          else
            echo "First commit or invalid before SHA - enabling all jobs"
          fi
          echo "build_container=true" >> $GITHUB_OUTPUT
          echo "k8s_changed=true" >> $GITHUB_OUTPUT
          echo "cf_changed=true" >> $GITHUB_OUTPUT
          echo "config_changed_non_prod=true" >> $GITHUB_OUTPUT
          echo "config_changed_prod=true" >> $GITHUB_OUTPUT
          echo "  Build container: true"
          echo "  K8s changed: true"
          echo "  CloudFormation changed: true"
          echo "  Config changed (non-prod): true"
          echo "  Config changed (prod): true"
          echo "================================"
          exit 0
        fi

        # Get all changed files (run git diff once)
        if ! ALL_FILES=$(git diff --name-only "$event_before" "$event_sha" 2>&1); then
          echo "ERROR: git diff failed: $ALL_FILES"
          echo "Enabling all jobs as fallback"
          echo "build_container=true" >> $GITHUB_OUTPUT
          echo "k8s_changed=true" >> $GITHUB_OUTPUT
          echo "cf_changed=true" >> $GITHUB_OUTPUT
          echo "config_changed_non_prod=true" >> $GITHUB_OUTPUT
          echo "config_changed_prod=true" >> $GITHUB_OUTPUT
          echo "================================"
          exit 0
        fi

        # Debug: show all changed files
        if [[ -n "$ALL_FILES" ]]; then
          echo "Changed files:"
          echo "$ALL_FILES" | sed 's/^/  /'
          echo ""
        else
          echo "No files changed"
          echo ""
        fi

        # Escape special regex characters in paths
        k8s_pattern=$(echo "$k8s_path" | sed 's/\./\\./g')
        cf_pattern=$(echo "$cf_file" | sed 's/\./\\./g')

        # Check for K8s changes
        K8S_FILES=$(echo "$ALL_FILES" | grep -E "^${k8s_pattern}" || true)
        if [[ -n "$K8S_FILES" ]]; then
          echo "k8s_changed=true" >> $GITHUB_OUTPUT
          echo "  K8s changed: true"
          echo "$K8S_FILES" | sed 's/^/    - /'
        else
          echo "k8s_changed=false" >> $GITHUB_OUTPUT
          echo "  K8s changed: false"
        fi

        # Check for CloudFormation changes (match filename exactly)
        CF_FILES=$(echo "$ALL_FILES" | grep -E "(^|/)${cf_pattern}$" || true)
        if [[ -n "$CF_FILES" ]]; then
          echo "cf_changed=true" >> $GITHUB_OUTPUT
          echo "  CloudFormation changed: true"
          echo "$CF_FILES" | sed 's/^/    - /'
        else
          echo "cf_changed=false" >> $GITHUB_OUTPUT
          echo "  CloudFormation changed: false"
        fi

        # Check for ConfigMap/Secret changes in non-prod (files containing "configmap" or "secret")
        CONFIG_FILES_NON_PROD=$(echo "$ALL_FILES" | grep -E "^${k8s_pattern}non-prod/.*(configmap|secret).*\.yaml$" || true)
        if [[ -n "$CONFIG_FILES_NON_PROD" ]]; then
          echo "config_changed_non_prod=true" >> $GITHUB_OUTPUT
          echo "  Config changed (non-prod): true"
          echo "$CONFIG_FILES_NON_PROD" | sed 's/^/    - /'
        else
          echo "config_changed_non_prod=false" >> $GITHUB_OUTPUT
          echo "  Config changed (non-prod): false"
        fi

        # Check for ConfigMap/Secret changes in prod (files containing "configmap" or "secret")
        CONFIG_FILES_PROD=$(echo "$ALL_FILES" | grep -E "^${k8s_pattern}prod/.*(configmap|secret).*\.yaml$" || true)
        if [[ -n "$CONFIG_FILES_PROD" ]]; then
          echo "config_changed_prod=true" >> $GITHUB_OUTPUT
          echo "  Config changed (prod): true"
          echo "$CONFIG_FILES_PROD" | sed 's/^/    - /'
        else
          echo "config_changed_prod=false" >> $GITHUB_OUTPUT
          echo "  Config changed (prod): false"
        fi

        # Check for build changes (anything NOT k8s or CloudFormation)
        BUILD_FILES=$(echo "$ALL_FILES" | grep -vE "^${k8s_pattern}" | grep -vE "(^|/)${cf_pattern}$" || true)
        if [[ -n "$BUILD_FILES" ]]; then
          echo "build_container=true" >> $GITHUB_OUTPUT
          echo "  Build container: true"
          echo "$BUILD_FILES" | sed 's/^/    - /'
        else
          echo "build_container=false" >> $GITHUB_OUTPUT
          echo "  Build container: false"
        fi

        echo "================================"